# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1paZg9MGjn_Fc8HUYgBc7q6Lp7T3OCmAL
"""

print("Mindula Dilthushan")